[project]
name = "ros-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dm-control==1.0.16",
    "mujoco==3.1.3",
    "pin>=3.7.0",
    "rospkg>=1.6.0",
]
